-- Rule Flow Definitions
-- Insert sample rule flows for testing

INSERT INTO rule_flow (flow_key, flow_name, flow_definition, version, status, category, description, tenant_id, create_by, deleted) VALUES
('flow.settlement.hospital-basic', '住院费用基本结算流程', '{"nodes":[{"nodeId":"start-1","type":"start","label":"开始"},{"nodeId":"cond-identity","type":"condition","label":"身份校验"},{"nodeId":"formula-reimburse","type":"formula","label":"报销金额计算"},{"nodeId":"cond-cap","type":"condition","label":"封顶线校验"},{"nodeId":"end-1","type":"end","label":"结算完成"}],"edges":[{"source":"start-1","target":"cond-identity"},{"source":"cond-identity","target":"formula-reimburse"},{"source":"formula-reimburse","target":"cond-cap"},{"source":"cond-cap","target":"end-1"}]}', 1, 'active', 'settlement', '住院费用结算基本流程', 'T001', 'admin', 0),

('flow.settlement.resident-basic', '居民医保结算流程', '{"nodes":[{"nodeId":"start-1","type":"start","label":"开始"},{"nodeId":"cond-identity","type":"condition","label":"居民身份校验"},{"nodeId":"formula-staged","type":"formula","label":"阶梯式报销计算"},{"nodeId":"end-1","type":"end","label":"结算完成"}],"edges":[{"source":"start-1","target":"cond-identity"},{"source":"cond-identity","target":"formula-staged"},{"source":"formula-staged","target":"end-1"}]}', 1, 'active', 'settlement', '居民医保费用结算', 'T001', 'admin', 0),

('flow.drug.interaction-check', '药品配伍禁忌审核流程', '{"nodes":[{"nodeId":"start-1","type":"start","label":"开始"},{"nodeId":"formula-interaction","type":"formula","label":"十八反检测"},{"nodeId":"cond-block","type":"condition","label":"是否有禁忌"},{"nodeId":"end-pass","type":"end","label":"审核通过"},{"nodeId":"end-block","type":"end","label":"审核拦截"}],"edges":[{"source":"start-1","target":"formula-interaction"},{"source":"formula-interaction","target":"cond-block"},{"source":"cond-block","target":"end-block"},{"source":"cond-block","target":"end-pass"}]}', 1, 'active', 'drug', '处方配伍禁忌检查', 'T001', 'admin', 0),

('flow.quality.antibiotic', '抗菌药物使用质控流程', '{"nodes":[{"nodeId":"start-1","type":"start","label":"开始"},{"nodeId":"action-classify","type":"action","label":"抗菌药物分级"},{"nodeId":"cond-special","type":"condition","label":"特殊使用级"},{"nodeId":"action-warn","type":"action","label":"越级预警"},{"nodeId":"end-1","type":"end","label":"质控完成"}],"edges":[{"source":"start-1","target":"action-classify"},{"source":"action-classify","target":"cond-special"},{"source":"cond-special","target":"action-warn"},{"source":"action-warn","target":"end-1"}]}', 1, 'active', 'quality', '抗菌药物分级管理质控', 'T001', 'admin', 0),

('flow.drg.grouping', 'DRG分组判定流程', '{"nodes":[{"nodeId":"start-1","type":"start","label":"开始"},{"nodeId":"cond-surgery","type":"condition","label":"是否有手术操作"},{"nodeId":"formula-drg-surgery","type":"formula","label":"手术DRG分组"},{"nodeId":"formula-drg-medical","type":"formula","label":"内科DRG分组"},{"nodeId":"end-1","type":"end","label":"分组完成"}],"edges":[{"source":"start-1","target":"cond-surgery"},{"source":"cond-surgery","target":"formula-drg-surgery"},{"source":"cond-surgery","target":"formula-drg-medical"},{"source":"formula-drg-surgery","target":"end-1"},{"source":"formula-drg-medical","target":"end-1"}]}', 1, 'draft', 'drg', '基于ICD诊断和操作进行DRG自动分组', 'T001', 'admin', 0),

('flow.settlement.medicare-aid', '医疗救助结算流程', '{"nodes":[{"nodeId":"start-1","type":"start","label":"开始"},{"nodeId":"cond-aid","type":"condition","label":"救助身份校验"},{"nodeId":"formula-basic","type":"formula","label":"基本医保计算"},{"nodeId":"formula-supplement","type":"formula","label":"医疗救助计算"},{"nodeId":"end-1","type":"end","label":"结算完成"}],"edges":[{"source":"start-1","target":"cond-aid"},{"source":"cond-aid","target":"formula-basic"},{"source":"formula-basic","target":"formula-supplement"},{"source":"formula-supplement","target":"end-1"}]}', 1, 'active', 'settlement', '医疗救助对象费用结算', 'T001', 'admin', 0),

('flow.drug.prescription-review', '处方前置审核流程', '{"nodes":[{"nodeId":"start-1","type":"start","label":"开始"},{"nodeId":"formula-indication","type":"formula","label":"适应症匹配"},{"nodeId":"formula-dosage","type":"formula","label":"用法用量检查"},{"nodeId":"cond-error","type":"condition","label":"是否有错误"},{"nodeId":"end-pass","type":"end","label":"审核通过"},{"nodeId":"end-fail","type":"end","label":"审核不通过"}],"edges":[{"source":"start-1","target":"formula-indication"},{"source":"formula-indication","target":"formula-dosage"},{"source":"formula-dosage","target":"cond-error"},{"source":"cond-error","target":"end-fail"},{"source":"cond-error","target":"end-pass"}]}', 1, 'active', 'drug', '医生开处方时实时审核', 'T001', 'admin', 0),

('flow.quality.infection', '院感监测流程', '{"nodes":[{"nodeId":"start-1","type":"start","label":"开始"},{"nodeId":"formula-infection-rate","type":"formula","label":"感染率计算"},{"nodeId":"cond-threshold","type":"condition","label":"超阈值预警"},{"nodeId":"action-alert","type":"action","label":"发送预警"},{"nodeId":"end-1","type":"end","label":"监测完成"}],"edges":[{"source":"start-1","target":"formula-infection-rate"},{"source":"formula-infection-rate","target":"cond-threshold"},{"source":"cond-threshold","target":"action-alert"},{"source":"action-alert","target":"end-1"}]}', 1, 'active', 'quality', '医院感染监测与预警', 'T001', 'admin', 0),

('flow.settlement.critical-illness', '大病保险结算流程', '{"nodes":[{"nodeId":"start-1","type":"start","label":"开始"},{"nodeId":"formula-self-pay","type":"formula","label":"自付金额计算"},{"nodeId":"cond-threshold","type":"condition","label":"超大病起付线"},{"nodeId":"formula-disease","type":"formula","label":"大病报销计算"},{"nodeId":"end-1","type":"end","label":"结算完成"}],"edges":[{"source":"start-1","target":"formula-self-pay"},{"source":"formula-self-pay","target":"cond-threshold"},{"source":"cond-threshold","target":"formula-disease"},{"source":"formula-disease","target":"end-1"}]}', 1, 'active', 'settlement', '大病保险二次报销计算', 'T001', 'admin', 0),

('flow.quality.blood-use', '临床用血审核流程', '{"nodes":[{"nodeId":"start-1","type":"start","label":"开始"},{"nodeId":"formula-indication","type":"formula","label":"用血指征审核"},{"nodeId":"formula-amount","type":"formula","label":"用血量审核"},{"nodeId":"cond-approve","type":"condition","label":"审批通过"},{"nodeId":"end-pass","type":"end","label":"审批通过"},{"nodeId":"end-reject","type":"end","label":"审批拒绝"}],"edges":[{"source":"start-1","target":"formula-indication"},{"source":"formula-indication","target":"formula-amount"},{"source":"formula-amount","target":"cond-approve"},{"source":"cond-approve","target":"end-pass"},{"source":"cond-approve","target":"end-reject"}]}', 1, 'draft', 'quality', '临床用血审批流程', 'T001', 'admin', 0);
